# Name and version of this dbt project.
name: 'devkit_connector'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'devkit_connector'

vars:
  # Set the used database. Supported options: "sqlserver", "snowflake".
  database: "sqlserver"
  # Name of the schema where the raw input data is stored.
  schema: "devkit_connector"
  # Configuration to use pm-utils package.
  date_format: 23 # sqlserver: 23, snowflake: 'YYYY-MM-DD'
  time_format: 8 # sqlserver: 8, snowflake: 'hh24:mi:ss'
  datetime_format: 20 # sqlserver: 20, snowflake: 'YYYY-MM-DD hh24:mi:ss.ff3'

# These configurations specify where dbt should look for different types of files.
source-paths: ["models"]
macro-paths: ["macros"]

# Directory which will store compiled SQL files and will be removed by 'dbt clean'.
target-path: "target"
clean-targets:
  - "target"

# All models are materialized as tables by default.
models:
  +materialized: table

# Quoting is enabled for databases, schemas, and identifiers.
quoting:
  database: true
  schema: true
  identifier: true
