devkit_connector:
  outputs:

    sqlserver:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: 
      port: 1433
      user:
      password:
      database:
      schema: "devkit_connector"

    snowflake:
      type: snowflake
      account:
      user:
      password:
      role:
      database:
      warehouse:
      schema: "devkit_connector"

    sqlserver-ci:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'
      server: pm-da.westeurope.cloudapp.azure.com
      port: 1433
      user: "dev_user"
      password: "{{ env_var('DBT_SQLSERVER_PASSWORD') }}"
      database: "{{ var('database') }}"
      schema: "{{ var('schema_target') }}"

    snowflake-ci:
      type: snowflake
      account: uipathalpha.west-europe.azure
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: PMC_CONNECTOR_ROLE
      database: PMC_CONNECTOR
      warehouse: PMC_WH_DEV
      schema: "{{ var('schema_target') }}"

  target: sqlserver
