name: Deliverables

parameters:
  - name: isTemplateOneConnector
    type: string
    default: true

resources:
  repositories:
    - repository: deliverablesCheck
      endpoint: UiPath
      type: github
      name: UiPath/ProcessMining-framework-resources
      ref: feat/partner_feedback

# The pipeline runs on PRs to main or validation, not on pushes to other branches.
trigger:
  none

pr:
  none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: deliverables_complete
    steps:
      - template: ./.pipelines/templates/deliverables_check.job.yml@deliverablesCheck
        parameters:
          isTemplateOneConnector: ${{ parameters.isTemplateOneConnector }}
