name: Transformations

parameters:
  - name: dbtVariableConfigurationSQLServer
    type: string
    default: ''
  - name: dbtVariableConfigurationSnowflake
    type: string
    default: ''
  - name: serviceConnection
    type: string
    default: 'pmc-dev-config-kv-sc'

resources:
  repositories:
    - repository: toggleKeyVaultRepo
      endpoint: UiPath
      type: github
      name: UiPath/AzurePipelinesTemplates
      ref: refs/tags/uipath.kv-access.1.2.1

    - repository: dbtTransformations
      endpoint: UiPath
      type: github
      name: UiPath/ProcessMining-framework-resources
      ref: refs/tags/dbt_transformations.0.1.2

    - repository: sqlfluffLinter
      endpoint: UiPath
      type: github
      name: UiPath/ProcessMining-framework-resources
      ref: feat/partner_feedback

    - repository: slackmessages
      type: GitHub
      endpoint: UiPath
      name: UiPath/AzurePipelinesTemplates
      ref: refs/tags/uipath.post-slack-message.1.1.2

# By leaving the trigger undefined, the pipeline starts on each push to any branch.
# Therefore it is not necessary to also start it via a PR.
pr:
  none

pool:
  vmImage: ubuntu-latest

jobs:
  - job: test_dbt_transformations
    steps:
      - template: ./.pipelines/templates/test.dbt_transformations.job.yml@dbtTransformations
        parameters:
          dbtVariableConfigurationSQLServer: ${{ parameters.dbtVariableConfigurationSQLServer }}
          dbtVariableConfigurationSnowflake: ${{ parameters.dbtVariableConfigurationSnowflake }}
          serviceConnection: ${{ parameters.serviceConnection }}

  - job: lint_sql
    steps:
      - template: ./.pipelines/templates/sqlfluff_lint.job.yml@sqlfluffLinter
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}

  - job: post_failure_to_slack
    dependsOn: 
      - test_dbt_transformations
      - lint_sql
    steps:
      - template: AzurePipelines/post-slack-message.yml@slackmessages
        parameters:
          condition: failed() #will send the notification if one ore more steps (in the same job) before this one have failed
          message: "Failed to run the pipeline $(Build.DefinitionName)"
          messageAuthor: "Pipeline gods"
          channel: "pmc-devops-alerts-playground"
          useExistingSlackMessagesApp: true
          azureInternalProdEAConnectionName: 'Internal-Production-EA' #Required if useExistingSlackMessagesApp is true
