version: 2

# Sources point to the tables in the database that contain the raw input data.
# You can refer to these sources in the models by using the {{ source() }} jinja function.
sources:
  - name: sources
    schema: "{{ var('schema_sources', target.schema) }}"
    tables:
      - name: Transaction_history
        columns:
          - name: '"ID"'
            tests:
              - pm_utils.not_null
          - name: '"Timestamp"'
            tests:
              - pm_utils.not_null:
                  severity: warn
      - name: INV
        columns:
          - name: '"ID"'
            tests:
              - pm_utils.not_null
              - pm_utils.unique
          - name: '"Created_at"'
            tests:
              - pm_utils.not_null:
                  severity: warn
      - name: PO_approvals
        columns:
          - name: '"ID"'
            tests:
              - pm_utils.not_null
          - name: '"Approved_at"'
            tests:
              - pm_utils.not_null:
                  severity: warn
      - name: PO
        columns:
          - name: '"ID"'
            tests:
              - pm_utils.not_null
              - pm_utils.unique
      - name: PO_status
      - name: Users

    # Enabled quoting for databases, schemas, and identifiers where the sources are located.
    quoting:
      database: true
      schema: true
      identifier: true
